import Head from 'next/head';
import React, { ReactNode } from 'react';

interface ILayoutProps {
    children: ReactNode;
}

export default function Layout({ children }: ILayoutProps) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/AtomicDesign/atomic-design_v1/public/favicon.ico"
                />
            </Head>
            <header>헤더</header>
            <div className="container">{children}</div>
            <footer>푸터</footer>
        </>
    );
}
