import Head from 'next/head';
import React, { ReactNode, useEffect, useRef } from 'react';

interface ILayoutProps {
  children: ReactNode;
}

export default function Layout({ children }: ILayoutProps) {
  const header = useRef<HTMLElement>(null);
  const footer = useRef<HTMLElement>(null);
  const container = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handlerReneder = () => {
      container.current!.style.minHeight = `${
        window.innerHeight - (header.current!.offsetHeight + footer.current!.offsetHeight)
      }px`;
    };

    handlerReneder();

    window.addEventListener('resize', handlerReneder);

    return () => window.removeEventListener('resize', handlerReneder);
  }, []);

  return (
    <>
      <Head>
        <title>Atomic Design Pattern</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/AtomicDesign/atomic-design_v1/public/favicon.ico" />
      </Head>
      <div className="wrapper">
        <header ref={header}>헤더</header>
        <div ref={container} className="container">
          {children}
        </div>
        <footer ref={footer}>푸터</footer>
      </div>
    </>
  );
}
